export const Countries = {
    AR: "Argentina (AR)",
    BO: "Bolivia (BO)",
    BR: "Brasil (BR)",
    CL: "Chile (CL)",
    CO: "Colombia (CO)",
    CR: "Costa Rica (CR)",
    EC: "Ecuador (EC)",
    SV: "El Salvador (SV)",
    GT: "Guatemala (GT)",
    HN: "Honduras (HN)",
    MX: "México (MX)",
    NI: "Nicaragua (NI)",
    PA: "Panamá (PA)",
    PY: "Paraguay (PY)",
    PE: "Perú (PE)",
    DO: "República Dominicana (DO)",
    UY: "Uruguay (UY)",
    VE: "Venezuela (VE)",
    US: "Estados Unidos (US)",
    CA: "Canadá (CA)",
    JM: "Jamaica (JM)",
    ES: "España (ES)",
    FR: "Francia (FR)",
    DE: "Alemania (DE)",
    IT: "Italia (IT)",
    PT: "Portugal (PT)",
    IE: "Irlanda (IE)",
    NL: "Países Bajos (NL)",
    GB: "Reino Unido (GB)",
    JP: "Japón (JP)",
    KR: "Corea del Sur (KR)",
    CN: "China (CN)",
    IN: "India (IN)",
    SG: "Singapur (SG)",
    AE: "Emiratos Árabes Unidos (AE)",
    AU: "Australia (AU)",
    NZ: "Nueva Zelanda (NZ)",
    ZA: "Sudáfrica (ZA)",
    NG: "Nigeria (NG)",
    EG: "Egipto (EG)"
} as const;